name: Release Binary

on: 
  workflow_dispatch:
  push:
    tags:
      - v*

permissions: 
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.19

      - name: Release on GitHub
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean
          version: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


          
        
    
    